### PR TITLE
Provide keys through autoImport

### LINKED ISSUE #30: keys should do the right autoPlugin dance
so that e.g. this doesn't happen:

```
> show mimaPreviousVersion
[info] Some(1.0.6)
> set mimaPreviousVersion := None
<set>:1: error: not found: value mimaPreviousVersion
mimaPreviousVersion := None
```

(note `set ScalaModulePlugin.mimaPreviousVersion := None` works)

and that this isn't needed:

```
import ScalaModulePlugin._
```

@dwijnand describes the dance as "autoImport (or aliases, or mixed-in, or whatever)"

### PR DESCRIPTION
**Pull request by Philippus**
fixes #30

### CODE REVIEW

**Comment by SethTisue** [comment]
review by @eed3si9n ?

File: src/main/scala/ScalaModulePlugin.scala [hunk 1]
```diff
@@ -11,9 +11,13 @@ import sbt.librarymanagement.ivy.IvyDependencyResolution
 import sbt.librarymanagement.{ UnresolvedWarningConfiguration, UpdateConfiguration }
 
 object ScalaModulePlugin extends AutoPlugin {
-  val repoName            = settingKey[String]("The name of the repository under github.com/scala/.")
-  val mimaPreviousVersion = settingKey[Option[String]]("The version of this module to compare against when running MiMa.")
-  val scalaVersionsByJvm  = settingKey[Map[Int, List[(String, Boolean)]]]("For a Java major version (6, 8, 9), a list of a Scala version and a flag indicating whether to use this combination for publishing.")
+  object autoImport {
+    val repoName = settingKey[String]("The name of the repository under github.com/scala/.")
```
Comment (eed3si9n) [inline src/main/scala/ScalaModulePlugin.scala]: sbt Plugins Best Practice recommends that we use plugin-specific prefix for all keys to avoid conflict - https://www.scala-sbt.org/1.x/docs/Plugins-Best-Practices.html#Key+naming+convention%3A+Use+prefix

If we are making these keys available automatically via autoImport, we should use our own prefix.

File: src/main/scala/ScalaModulePlugin.scala [hunk 2]
```diff
@@ -11,9 +11,13 @@ import sbt.librarymanagement.ivy.IvyDependencyResolution
...
+    val mimaPreviousVersion = settingKey[Option[String]]("The version of this module to compare against when running MiMa.")
```
Comment (eed3si9n) [inline src/main/scala/ScalaModulePlugin.scala]: `mima` is a prefix used by MiMa plugin, so this especially seems bad, as it would cause a conflict if MiMa decides to add this feature.

**Comment by eed3si9n** [comment]
Could you rebase this plz?

**Comment by lrytz** [comment]
Thanks, @Philippus!
